import Head from 'next/head';
import Image from 'next/image';
import Header from '../components/Header';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Hulu clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <h1>🚀Hulu</h1> */}

      {/* Header */}
      <Header />

      {/* Nav */}

      {/* Results */}
    </div>
  );
}
